#server:
#  port: 8888
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  shardingsphere:
#    datasource:
#      names: master,slave0,slave1
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3339/im_bis?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#        username: root
#        password: 123456
#      slave0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3340/im_bis?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#        username: root
#        password: 123456
#      slave1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3341/im_bis?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#        username: root
#        password: 123456
#    masterslave:
#      load-balance-algorithm-type: round_robin
#      name: ms
#      master-data-source-name: master
#      slave-data-source-names: slave0,slave1
#    sharding:
#      binding-tables:
#        im_team_message:
#          key-generator.column: id
#          key-generator:
#            type: SNOWFLAKE
#            props:
#              worker:
#                id: 123
#    props:
#      sql:
#        show: true
#mybatis:
#  type-aliases-package: com.zzx.sharding.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 3000
#  mapper-locations: classpath*:mapper/*.xml
#
#
#
